### PR TITLE
Feature/entity mapping

### PR DESCRIPTION
**Pull request by mike-hanson**
Finally completed entity graph mapping, cleaned up the branches to remove SQLLite work to avoid complication.

If you are happy with this I propose to go ahead and release as v3, existing code should work as before after update but I changed a lot so I think it is worth a major version increment

### CODE REVIEW

**Comment by testpossessed** [comment]
Starting to write the docs I realised a couple of things.

1. I haven't implemented the profile mapping for ad-hoc SQL queries or query stored procs, taking care of this now.

2. I think we need a factory for EntityMappingProfile<T> as much as anything to support testing as we do encourage with statement building

**Comment by testpossessed** [comment]
To get a good idea of what I have done it is worth looking at DataReaderEntityMapperShould.cs as these tests demonstrate pretty much everything from a mapping perspective and includes tests for nesting two two levels i.e. Parent > Child > Grand Child

**Comment by testpossessed** [comment]
I want to release this so I can get on with the SQLite support so going to merge without waiting for reviews

**Comment by markiodev** [comment]
Sorry I didn't get round to checking this out, will be sure to have a look at the changes when I can.

**Comment by mike-hanson** [comment]
No worries, I walked Faustina through it and she seemed happy so pushed it through so I could press on with SQLite support

**Pull request merged**
